apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{ .Values.selector | toYaml }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.selector | toYaml }}
  template:
    metadata:
      labels:
        {{ .Values.selector | toYaml }}
    spec:
      containers:
        - name: static-server
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-conf
            - mountPath: /var/www/static/archives
              name: archives-data
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-static-server-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: archives-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-archives-volume-claim
