apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          volumeMounts:
            - mountPath: /data
              name: data-redis
      volumes:
        - name: data-redis
          persistentVolumeClaim:
            claimName: redis-volume-claim
