apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  labels:
    app: auth-api
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: trycatchf1nally/archive-cloud-auth-api:1.0.0
          env:
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: FRONTEND_ORIGIN
              value: http://localhost
            - name: AUTH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-keys
                  key: public-key
            - name: AUTH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-keys
                  key: private-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-keys
                  key: jwt-secret
