apiVersion: v1
kind: ConfigMap
metadata:
  name: static-server-nginx-conf
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
  
    http {
      include /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile on;
  
      server {
        listen 80;
        listen [::]:80 default ipv6only=on;
      
        root /var/www/static/;
      }
    }
