apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
  labels:
    app: static-server
spec:
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      labels:
        app: static-server
    spec:
      containers:
        - name: static-server
          image: trycatchf1nally/archive-cloud-static-server:1.0.0
          volumeMounts:
            - mountPath: /var/www/static/archives
              name: archives-data
      volumes:
        - name: archives-data
          persistentVolumeClaim:
            claimName: archives-volume-claim
