apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6
          volumeMounts:
            - mountPath: /data/db
              name: data-mongodb
      volumes:
        - name: data-mongodb
          persistentVolumeClaim:
            claimName: mongodb-volume-claim
