version: "3.8"

name: archive-cloud

services:
  client:
    build:
      context: ../services/client
      args:
        REACT_APP_API_GATEWAY: ${API_GATEWAY}
    networks:
      - client-reverse-proxy

  auth-api:
    build: ../services/auth-api
    environment:
      MONGODB_HOST: mongodb
      FRONTEND_ORIGIN: ${API_GATEWAY}
      AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
      AUTH_PRIVATE_KEY: ${AUTH_PRIVATE_KEY}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - auth-api-reverse-proxy
      - auth-api-mongodb
    depends_on:
      - mongodb

  upload-api:
    build: ../services/upload-api
    environment:
      REDIS_HOST: redis
      FRONTEND_ORIGIN: ${API_GATEWAY}
      STORAGE_API_ORIGIN: http://storage-api:3000
      AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
    volumes:
      - uploads:/usr/src/app/uploads
      - archives:/usr/src/app/archives
    networks:
      - upload-api-reverse-proxy
      - upload-api-storage-api
      - upload-api-redis
    depends_on:
      - redis
      - storage-api

  storage-api:
    build: ../services/storage-api
    environment:
      MONGODB_HOST: mongodb
      FRONTEND_ORIGIN: ${API_GATEWAY}
      AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
    volumes:
      - archives:/usr/src/app/archives
    networks:
      - storage-api-reverse-proxy
      - upload-api-storage-api
      - storage-api-mongodb
    depends_on:
      - mongodb
      - storage-api-mongodb-migration

  reverse-proxy:
    image: nginx:1.24.0
    ports:
      - "3000:80" # exposed port should be the port of API gateway see (see .env file)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - client-reverse-proxy
      - auth-api-reverse-proxy
      - upload-api-reverse-proxy
      - storage-api-reverse-proxy
      - static-server-reverse-proxy

  static-server:
    build: ../services/static-server
    volumes:
      - archives:/var/www/static/archives/
    networks:
      - static-server-reverse-proxy

  storage-api-mongodb-migration:
    build: ../services/storage-api/migrate-mongo
    environment:
      MONGODB_HOST: mongodb
    volumes:
      - archives:/app/archives
    networks:
      - storage-api-mongodb-migration-mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    volumes:
      - mongodb-data:/data/db
    networks:
      - auth-api-mongodb
      - storage-api-mongodb
      - storage-api-mongodb-migration-mongodb

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    networks:
      - upload-api-redis

volumes:
  archives:
  uploads:
  mongodb-data:
  redis-data:

networks:
  client-reverse-proxy:
  auth-api-reverse-proxy:
  upload-api-reverse-proxy:
  storage-api-reverse-proxy:
  static-server-reverse-proxy:
  upload-api-storage-api:
  auth-api-mongodb:
  storage-api-mongodb:
  storage-api-mongodb-migration-mongodb:
  upload-api-redis:
