version: "3.8"

name: archive-cloud

services:
  client:
    build:
      context: ../services/client
      args:
        REACT_APP_API_GATEWAY: ${API_GATEWAY}
    networks:
      - application

  auth-api:
    build: ../services/auth-api
    environment:
      MONGODB_HOST: mongodb
      LOGSTASH_HOST: logstash
      FRONTEND_ORIGIN: ${API_GATEWAY}
      AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
      AUTH_PRIVATE_KEY: ${AUTH_PRIVATE_KEY}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - application
    depends_on:
      - mongodb
      - logstash

  upload-api:
    build: ../services/upload-api
    environment:
      REDIS_HOST: redis
      KAFKA_HOST: kafka
      LOGSTASH_HOST: logstash
      FRONTEND_ORIGIN: ${API_GATEWAY}
      STORAGE_API_ORIGIN: http://storage-api:3000
      AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
    volumes:
      - uploads:/usr/src/app/uploads
      - archives:/usr/src/app/archives
    networks:
      - application
    depends_on:
      - redis
      - kafka
      - logstash

  storage-api:
    build: ../services/storage-api
    environment:
      MONGODB_HOST: mongodb
      KAFKA_HOST: kafka
      LOGSTASH_HOST: logstash
      FRONTEND_ORIGIN: ${API_GATEWAY}
      AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
    volumes:
      - archives:/usr/src/app/archives
    networks:
      - application
    depends_on:
      - mongodb
      - storage-api-mongodb-migration
      - kafka
      - logstash

  reverse-proxy:
    image: nginx:1.24.0
    ports:
      - "3000:80" # exposed port should be the port of API gateway see (see .env file)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - application

  static-server:
    image: nginx:1.24.0
    volumes:
      - ../services/static-server/nginx.conf:/etc/nginx/nginx.conf
      - archives:/var/www/static/archives/
    networks:
      - application

  storage-api-mongodb-migration:
    build: ../services/storage-api/migrate-mongo
    environment:
      MONGODB_HOST: mongodb
    volumes:
      - archives:/app/archives
    networks:
      - application
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    volumes:
      - mongodb-data:/data/db
    networks:
      - application

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    networks:
      - application

  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    networks:
      - application

  kafka:
    image: bitnami/kafka:3
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - application
    depends_on:
      - zookeeper

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    command: sh -c "logstash -f /usr/share/logstash/config/logstash.conf"
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
    networks:
      - application
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data/
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    networks:
      - application

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - application
    depends_on:
      - elasticsearch

volumes:
  archives:
  uploads:
  mongodb-data:
  redis-data:
  zookeeper-data:
  kafka-data:
  elasticsearch-data:
  kibana-data:

networks:
  application:
