version: "3.8"

name: archive-cloud

services:
  client:
    build:
      context: ../client
      args:
        REACT_APP_AUTH_API_URL: http://localhost:8080/auth-api
        REACT_APP_UPLOAD_API_URL: http://localhost:8080/upload-api
        REACT_APP_STORAGE_API_URL: http://localhost:8080/storage-api
    ports:
      - "3000:80"

  auth-api:
    build: ../auth-api
    environment:
      MONGODB_URI: mongodb://mongodb:27017/auth-api
      FRONTEND_ORIGIN: http://localhost:3000
      AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
      AUTH_PRIVATE_KEY: ${AUTH_PRIVATE_KEY}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - auth-api-network

  upload-api:
    build: ../upload-api
    environment:
      REDIS_HOST: redis
      FRONTEND_ORIGIN: http://localhost:3000
      STORAGE_API_ORIGIN: http://storage-api:3000
      AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
      USE_SYSTEM_7ZA: true
    volumes:
      - uploads:/usr/src/app/uploads
      - archives:/usr/src/app/archives
    networks:
      - upload-api-network
      - upload-api-storage-api-network
    depends_on:
      - redis

  storage-api:
    build: ../storage-api
    environment:
      MONGODB_URI: mongodb://mongodb:27017/storage-api
      FRONTEND_ORIGIN: http://localhost:3000
      AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
    volumes:
      - archives:/usr/src/app/archives
    networks:
      - storage-api-network
      - upload-api-storage-api-network
    depends_on:
      - mongodb

  nginx:
    image: nginx:1.24.0
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - auth-api-network
      - upload-api-network
      - storage-api-network
      - upload-api-storage-api-network

  mongodb:
    image: mongo:6
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    volumes:
      - mongodb-data:/data/db
    networks:
      - auth-api-network
      - storage-api-network

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    networks:
      - upload-api-network

volumes:
  archives:
  uploads:
  mongodb-data:
  redis-data:

networks:
  auth-api-network:
  upload-api-network:
  storage-api-network:
  upload-api-storage-api-network:
