replicaCount: 1

selector:
  app: upload-api

image:
  name: trycatchf1nally/archive-cloud-upload-api
  tag: 1.0.1

service:
  port: 80
  targetPort: 3000

ingress:
  path: /api/upload

archivesVolume: 5Gi

configs:
  REDIS_HOST: archive-cloud-redis-master
  REDIS_PORT: 6379
  KAFKA_HOST: archive-cloud-kafka
  KAFKA_PORT: 9092
  FRONTEND_ORIGIN: http://localhost
