replicaCount: 2

selector:
  app: storage-api

image:
  name: trycatchf1nally/archive-cloud-storage-api
  tag: 1.0.0
service:
  port: 80
  targetPort: 3000
ingress:
  path: /api/storage
migrations:
  image:
    name: trycatchf1nally/archive-cloud-storage-api-mongodb-migration
    tag: 1.0.0
archivesVolume: 10Gi
configs:
  MONGODB_HOST: archive-cloud-mongodb
  MONGODB_PORT: 27017
  FRONTEND_ORIGIN: http://localhost
