apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-api
  labels:
    app: storage-api
spec:
  selector:
    matchLabels:
      app: storage-api
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      containers:
        - name: storage-api
          image: trycatchf1nally/archive-cloud-storage-api:v1.0.0
          volumeMounts:
            - mountPath: /usr/src/app/archives
              name: archives-data
          env:
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: FRONTEND_ORIGIN
              value: http://localhost
            - name: AUTH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-keys
                  key: public-key
      volumes:
        - name: archives-data
          persistentVolumeClaim:
            claimName: archives-volume-claim
