apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-keys
data:
  public-key: {{ .Values.secrets.AUTH_PUBLIC_KEY }}
  private-key: {{ .Values.secrets.AUTH_PRIVATE_KEY }}
  jwt-secret: {{ .Values.secrets.JWT_SECRET }}
