apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{ .Values.selector | toYaml }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.selector | toYaml }}
  template:
    metadata:
      labels:
        {{ .Values.selector | toYaml }}
    spec:
      initContainers:
        - name: migrate-mongo
          image: {{ .Values.migrations.image.name }}:{{ .Values.image.tag }}
          volumeMounts:
            - mountPath: /app/archives
              name: archives-data
          env:
            - name: MONGODB_HOST
              value: {{ .Values.configs.MONGODB_HOST }}
            - name: MONGODB_PORT
              value: {{ .Values.configs.MONGODB_PORT | quote }}
      containers:
        - name: storage-api
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          volumeMounts:
            - mountPath: /usr/src/app/archives
              name: archives-data
          env:
            - name: MONGODB_HOST
              value: {{ .Values.configs.MONGODB_HOST }}
            - name: MONGODB_PORT
              value: {{ .Values.configs.MONGODB_PORT | quote }}
            - name: FRONTEND_ORIGIN
              value: {{ .Values.configs.FRONTEND_ORIGIN }}
            - name: AUTH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-auth-keys
                  key: public-key
      volumes:
        - name: archives-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-archives-volume-claim
