apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "common.fullname" . }}-virtual
spec:
  hosts:
    - {{ include "common.fullname" . }}
  http:
    - route:
        - destination:
            host: {{ include "common.fullname" . }}
      timeout: 10s
      retries:
        attempts: 3
        retryOn: 5xx
        perTryTimeout: 5s
